language: cpp
sudo: false
compiler:
  - gcc

# Cache .npm folder for faster npm install
cache:
  directories:
    - $HOME/.npm

env:
  global:
    - GCC_VERSION="4.8"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    #Build dependencies:
    - cmake3
    - g++-4.8 # Required for latest libstdc++6

install:
# Emscripten
  - git clone https://github.com/juj/emsdk.git
  - cd emsdk
  - ./emsdk install sdk-1.37.37-64bit
  - ./emsdk activate sdk-1.37.37-64bit
  - source ./emsdk_env.sh
  - cd ..
# Grunt
  - npm install -g grunt-cli
# GDevelop
  - git clone https://github.com/4ian/GDevelop.git
  - cd GDevelop && git clone -b refactor/emscripten-build https://github.com/4ian/GDevelop.js.git
  - cd GDevelop.js
  - npm install
  - npm run build

script:
#GDCore and GDCpp game engine tests:
  - npm test